export const REGIONS = ["GO", "SP", "DF", "MG"];

export interface PredefinedLocation {
  name: string;
  region: string;
}

export const PREDEFINED_LOCATIONS: PredefinedLocation[] = [
  { name: "Volkswagen T7", region: "GO" },
  { name: "Toyota T7", region: "GO" },
  { name: "RAM Castelo Branco", region: "GO" },
  { name: "Marketing Galpão", region: "GO" },
  { name: "Compliance", region: "GO" },
  { name: "Primeira Mão T7", region: "GO" },
  { name: "Primeira Mão Off Road T7", region: "GO" },
  { name: "BYD Marista", region: "GO" },
  { name: "Tudo Chevrolet Mutirão", region: "GO" },
  { name: "Nissan 85", region: "GO" },
  { name: "Primeira Mão 85", region: "GO" },
  { name: "BMW Carros", region: "GO" },
  { name: "CRT", region: "GO" },
  { name: "Jeep / RAM BR", region: "GO" },
  { name: "Triumph", region: "GO" },
  { name: "BMW Motos", region: "GO" },
  { name: "Seminovos Motos", region: "GO" },
  { name: "Tudo Chevrolet Buriti", region: "GO" },
  { name: "Toyota Buriti", region: "GO" },
  { name: "Primeira Mão Buriti", region: "GO" },
  { name: "Hyundai T9", region: "GO" },
  { name: "Jeep T9", region: "GO" },
  { name: "BYD Cidade Jardim", region: "GO" },
  { name: "Hyundai Cidade Jardim", region: "GO" },
  { name: "Primeira Mão Cidade Jardim", region: "GO" },
  { name: "Outlet Shopping", region: "GO" },
  { name: "Primeira Mão Shopping", region: "GO" },
  { name: "Toyota Anapolis", region: "GO" },
  { name: "Hyundai Anapolis", region: "GO" },
  { name: "Primeira Mão Anapolis", region: "GO" },
  { name: "Jeep / RAM Anapolis", region: "GO" },
  { name: "Nissan Anapolis", region: "GO" },
  { name: "Fazendinha", region: "GO" },
  { name: "Primeira Mão Galpão", region: "GO" },
  { name: "Primeira Mão Digital Galpão", region: "GO" },
  { name: "Corretora", region: "GO" },
  { name: "Seguros", region: "GO" },
  { name: "CSC", region: "GO" },
  { name: "DP", region: "GO" },
  { name: "Contabilidade", region: "GO" },
  { name: "Controladoria", region: "GO" },
  { name: "Administrativo", region: "GO" },
  { name: "Diretoria", region: "GO" },
  { name: "Auditoria Galpão", region: "GO" },
  { name: "Compras Galpão", region: "GO" },
  { name: "RH Galpão", region: "GO" },
  { name: "Compras CRT", region: "GO" },
  { name: "CRT Galpão", region: "GO" },
  { name: "Marketing BYD", region: "GO" },
  { name: "CRM T.I", region: "GO" },
  { name: "Compliance Galpão", region: "GO" }
];
